# Generated by Django 4.2.7 on 2023-11-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polka', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polka.person'),
        ),
    ]
