# Generated by Django 4.2.7 on 2023-11-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polka', '0003_book_author2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
