# Generated by Django 4.2.7 on 2023-11-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polka', '0004_remove_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author2',
            new_name='author',
        ),
    ]
