# Generated by Django 4.2.7 on 2023-12-09 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polka', '0006_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(to='polka.book')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polka.person')),
            ],
        ),
    ]
