# Generated by Django 4.2.7 on 2023-12-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polka', '0008_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
