# Generated by Django 4.2.7 on 2023-12-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polka', '0010_alter_cart_books_cartitem_cart_books2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='books',
        ),
    ]
